apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prova-gio-rel
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: adapter
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: test-info 
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
