{{- if .Values.istio.ft_istio_175 }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "wphhc-adapter.name" . }}-peer-authentication
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "wphhc-adapter.name" . }}
  mtls:
    mode: {{ .Values.istio.mtlsMode }}
{{- end -}}    