apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "wphhc-adapter.name" . }}-destination-rule
  namespace: {{ .Values.namespace }}
  labels:
  {{ include "wphhc-adapter.labels" . | indent 2 }}
spec:
  host: {{ include "wphhc-adapter.name" . }}.{{ .Values.namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: {{ include "wphhc-adapter.name" . }}-subset-v1
    labels:
      app: {{ include "wphhc-adapter.name" . }}
      version: "1.0"